Add set up guide in README
Lenscrafters-Capstone/LensCrafters-free pull request #22
Opened 2023-11-11 17:21 UTC by JessicaJHee

Fixes #18

2023-11-12 08:53 UTC, o-farag commented
@JessicaJHee Good work, I really like the use of the venv.
One question, this is what happens when I run `pip install -r requirements`
![image](https://github.com/Lenscrafters-Capstone/LensCrafters-free/assets/15898988/51ee311e-a638-475a-a774-216cc1c42c67)
1. Did you mean for the file to have the .txt extension?
2. Are these errors ok i.e. expected (I can still run the app afterwards)
3. If not, were there any other steps you went through first?

2023-11-12 09:01 UTC, o-farag requested changes
Could you also add how to deactivate the venv? It's a simple `$ deactivate`  shell command once in the venv.

2023-11-12 14:48 UTC, JessicaJHee commented
@o-farag Yep nice catch, it was supposed to have the `.txt` extension.

What version of Python are you using? it should be 3.10.

2023-11-12 15:30 UTC, o-farag commented
> @o-farag Yep nice catch, it was supposed to have the `.txt` extension.
> 
> What version of Python are you using? it should be 3.10.

Oh ok I'm using 3.11, maybe the version should be mentioned as well.

2023-11-12 15:31 UTC, JessicaJHee commented on README.md
> +* Python 3.10
@o-farag mentioned here:

2023-11-13 00:34 UTC, o-farag commented on README.md
> +* Python 3.10
Woops hehe

2023-11-13 00:36 UTC, o-farag approved these changes
Thank you :)

2023-11-13 00:36 UTC, merged